//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFXIVVenues.BotGateway.VenueEvents.VenueSubscribing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SubscriptionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubscriptionStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFXIVVenues.BotGateway.VenueEvents.VenueSubscribing.SubscriptionStrings", typeof(SubscriptionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh, you&apos;re already subscribed to this venue! 😲.
        /// </summary>
        internal static string AlreadySubscribed {
            get {
                return ResourceManager.GetString("AlreadySubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no venue subscriptions, to subscribe to a venue, find it using /find then select subscribe in the action menu..
        /// </summary>
        internal static string NoSubscriptions {
            get {
                return ResourceManager.GetString("NoSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh, you&apos;re not subscribed to this venue! 🫨.
        /// </summary>
        internal static string NotSubscribed {
            get {
                return ResourceManager.GetString("NotSubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A venue you&apos;re subscribed to is opening soon!.
        /// </summary>
        internal static string OpeningSoonTitle {
            get {
                return ResourceManager.GetString("OpeningSoonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open {0} at {1}.
        /// </summary>
        internal static string OpenXFromNowAtY {
            get {
                return ResourceManager.GetString("OpenXFromNowAtY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yay, you&apos;re subscribed! I&apos;ll let you know when it&apos;ll open! 🥰.
        /// </summary>
        internal static string Subscribed {
            get {
                return ResourceManager.GetString("Subscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here&apos;s your subscribed venues! 🥰.
        /// </summary>
        internal static string SubscribedVenues {
            get {
                return ResourceManager.GetString("SubscribedVenues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay, you&apos;re unsubscribed! I&apos;ll stop messaging you about this venue. 🙏.
        /// </summary>
        internal static string Unsubscribed {
            get {
                return ResourceManager.GetString("Unsubscribed", resourceCulture);
            }
        }
    }
}
