<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>eaae95f8-4d05-4e1f-92e5-34083ecf7457</UserSecretsId>
    <RootNamespace>FFXIVVenues.BotGateway</RootNamespace>
    <AssemblyName>FFXIVVenues.BotGateway</AssemblyName>
    <SignAssembly>False</SignAssembly>
    <EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
    <DockerfileBuildArguments>--build-arg NUGET_REPO_PASSWORD=$(FFXIV_VENUES_NUGET_REPO_PASSWORD)</DockerfileBuildArguments>
    <LangVersion>latestmajor</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="VenueAuditing\AuditStrings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AuditStrings.resx</DependentUpon>
    </Compile>
    <Compile Update="VenueEvents\VenueFlags\FlagStrings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>FlagStrings.resx</DependentUpon>
    </Compile>
    <Compile Update="VenueEvents\VenueSubscribing\SubscriptionStrings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SubscriptionStrings.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="VenueAuditing\AuditStrings.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>AuditStrings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="VenueControl\VenueControlStrings.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>VenueControlStrings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Compile Update="VenueControl\VenueControlStrings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>VenueControlStrings.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="UserSupport\UserSupportStrings.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>UserSupportStrings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Compile Update="UserSupport\UserSupportStrings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>UserSupportStrings.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="AI\Davinci\ContextStrings.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ContextStrings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="VenueEvents\VenueFlags\FlagStrings.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>FlagStrings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="VenueEvents\VenueSubscribing\SubscriptionStrings.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>SubscriptionStrings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Compile Update="AI\Davinci\ContextStrings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ContextStrings.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Remove="FFXIVVenues.VenueModels" />
    <None Remove="PrettyPrintNet" />
    <None Remove="SixLabors.ImageSharp" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Azure.AI.Language.Conversations" Version="1.1.0" />
    <PackageReference Include="BetterStack.Logs.Serilog" Version="1.2.0" />
    <PackageReference Include="Discord.Net" Version="3.20.1" />
    <PackageReference Include="EPPlus" Version="8.6.1" />
    <PackageReference Include="Kana.Pipelines" Version="2.2.0" />
    <PackageReference Include="LiteDB" Version="5.0.21" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.9" />
    <PackageReference Include="moment.net" Version="2.0.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.9.0" />
    <PackageReference Include="Serilog" Version="4.3.1" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="FFXIVVenues.VenueModels" Version="14.2.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.9" />
    <PackageReference Include="TimeZoneConverter" Version="7.2.0" />
    <PackageReference Include="WolverineFx.RabbitMQ" Version="6.15.0" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" Version="6.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FFXIVVenues.DomainData\FFXIVVenues.DomainData.csproj" />
    <ProjectReference Include="..\FFXIVVenues.FlagService.Client\FFXIVVenues.FlagService.Client.csproj" />
    <ProjectReference Include="..\FFXIVVenues.ScheduleService.Client\FFXIVVenues.ScheduleService.Client.csproj" />
  </ItemGroup>


</Project>
