// <auto-generated />
using System;
using System.Collections.Generic;
using FFXIVVenues.DomainData.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FFXIVVenues.DomainData.Migrations
{
    [DbContext(typeof(DomainDataContext))]
    [Migration("20260208053528_ImproveLocationIndexes")]
    partial class ImproveLocationIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Venues")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FFXIVVenues.DomainData.Entities.Flags.Flag", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VenueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("Flag", "VenueFlags");
                });

            modelBuilder.Entity("FFXIVVenues.DomainData.Entities.Metrics.VenueView", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VenueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("VenueViews", "VenueMetrics");
                });

            modelBuilder.Entity("FFXIVVenues.DomainData.Entities.Venues.Location", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Apartment")
                        .HasColumnType("integer");

                    b.Property<string>("DataCenter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Override")
                        .HasColumnType("text");

                    b.Property<int>("Plot")
                        .HasColumnType("integer");

                    b.Property<int>("Room")
                        .HasColumnType("integer");

                    b.Property<bool>("Subdivision")
                        .HasColumnType("boolean");

                    b.Property<int>("Ward")
                        .HasColumnType("integer");

                    b.Property<string>("World")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DataCenter", "World", "District", "Ward", "Plot", "Apartment", "Room", "Subdivision" }, "DCAddress");

                    b.HasIndex(new[] { "Override" }, "Override");

                    b.HasIndex(new[] { "World", "District", "Ward", "Plot", "Apartment", "Room", "Subdivision" }, "WorldAddress");

                    b.ToTable("Locations", "Venues");
                });

            modelBuilder.Entity("FFXIVVenues.DomainData.Entities.Venues.Notice", b =>
                {
                    b.Property<string>("VenueId")
                        .HasColumnType("text");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("VenueId", "Id");

                    b.ToTable("Notices", "Venues");
                });

            modelBuilder.Entity("FFXIVVenues.DomainData.Entities.Venues.Schedule", b =>
                {
                    b.Property<string>("VenueId")
                        .HasColumnType("text");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<int>("StartHour")
                        .HasColumnType("integer");

                    b.Property<int>("StartMinute")
                        .HasColumnType("integer");

                    b.Property<int>("IntervalType")
                        .HasColumnType("integer");

                    b.Property<int>("IntervalArgument")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("Commencing")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EndHour")
                        .HasColumnType("integer");

                    b.Property<int?>("EndMinute")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VenueId", "Day", "StartHour", "StartMinute", "IntervalType", "IntervalArgument");

                    b.ToTable("Schedules", "Venues");
                });

            modelBuilder.Entity("FFXIVVenues.DomainData.Entities.Venues.ScheduleOverride", b =>
                {
                    b.Property<string>("VenueId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Open")
                        .HasColumnType("boolean");

                    b.HasKey("VenueId", "Start");

                    b.ToTable("ScheduleOverrides", "Venues");
                });

            modelBuilder.Entity("FFXIVVenues.DomainData.Entities.Venues.Venue", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Added")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<string>("Banner")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Deleted")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("Description")
                        .HasColumnType("text[]");

                    b.Property<string>("Discord")
                        .HasColumnType("text");

                    b.Property<bool>("Hiring")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocationId")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Managers")
                        .HasColumnType("text[]");

                    b.Property<string>("MareCode")
                        .HasColumnType("text");

                    b.Property<string>("MarePassword")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScopeKey")
                        .HasColumnType("text");

                    b.Property<bool>("Sfw")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .HasColumnType("text[]");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Venues", "Venues");
                });

            modelBuilder.Entity("FFXIVVenues.DomainData.Entities.Metrics.VenueView", b =>
                {
                    b.HasOne("FFXIVVenues.DomainData.Entities.Venues.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("FFXIVVenues.DomainData.Entities.Venues.Notice", b =>
                {
                    b.HasOne("FFXIVVenues.DomainData.Entities.Venues.Venue", "Venue")
                        .WithMany("Notices")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("FFXIVVenues.DomainData.Entities.Venues.Schedule", b =>
                {
                    b.HasOne("FFXIVVenues.DomainData.Entities.Venues.Venue", "Venue")
                        .WithMany("Schedule")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("FFXIVVenues.DomainData.Entities.Venues.ScheduleOverride", b =>
                {
                    b.HasOne("FFXIVVenues.DomainData.Entities.Venues.Venue", "Venue")
                        .WithMany("ScheduleOverrides")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("FFXIVVenues.DomainData.Entities.Venues.Venue", b =>
                {
                    b.HasOne("FFXIVVenues.DomainData.Entities.Venues.Location", "Location")
                        .WithMany("Venues")
                        .HasForeignKey("LocationId");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("FFXIVVenues.DomainData.Entities.Venues.Location", b =>
                {
                    b.Navigation("Venues");
                });

            modelBuilder.Entity("FFXIVVenues.DomainData.Entities.Venues.Venue", b =>
                {
                    b.Navigation("Notices");

                    b.Navigation("Schedule");

                    b.Navigation("ScheduleOverrides");
                });
#pragma warning restore 612, 618
        }
    }
}
